---
- name: ansible_pull demo
  hosts: localhost
  any_errors_fatal: true
  become: yes
  vars:

    # schedule is fed directly to cron
    schedule: '*/15 * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # Directory to where repository will be cloned
    workdir: /root/git-test1

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    #repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: git@github.com:Praneetmane/Ansible-Scripts.git 

  tasks:

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

    - name: Create crontab entry to clone/pull git repository
      template: 
          src: ansible-pull.j2  
          dest: /etc/cron.d/ansible-pull 
          owner: root 
          group: root 
          mode: 0644
