---
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of debian packages
  apt:
    name: "{{ debian | join(',') }}" 
    update_cache: true
    state: present

- name: Install list of python packages
  pip:
    name: "{{ python_pkgs | join(',') }}"

- name: Install list of npm packages
  npm:
    name: "{{ npm | join(',') }}"
    global: yes