---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../packages/vars

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ debian | join(',') }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ npm | join(',') }}"
